server:
  port: 8083

spring:
  application:
    name: community-api
  jersey:
    type: filter
    application-path: /api/v1
  datasource:
    url: jdbc:postgresql://localhost:5434/community_db
    username: citymate_community
    password: community_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: Cm2K9#xP7!vQ2@wR4eT6^yU8&iO0*aS1-dF3+gH5_jL9(kM2)nB4
