server:
  port: 8083

spring:
  application:
    name: community-api
  jersey:
    type: filter
    application-path: /api
  datasource:
    url: jdbc:postgresql://localhost:5432/community_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: "citymate-super-secret-key-must-be-at-least-256-bits-long"
